services:
  angular-frontend-nginx:
    build: client-generator-angular
    ports:
      - "81:80"
    depends_on:
      - nodejs-backend
  nodejs-backend:
    build: client-generator-backend
    ports:
      - "3334:3333"